[package]
name = "stad_demos"
version = "0.1.0"
authors = ["weston"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez="0.6.0-rc2"
#glam = "0.17.2"